[project]
navbar = [ { name = "Home ğŸ°", src = "/" }
         , { name = "Photos ğŸ“¸", src = "/photos" }
         , { name = "Projects ğŸ› ï¸", src = "/projects" }
         , { name = "Links ğŸŒ±", src = "/where" }
         ]
